global:
  scrape_interval: 5s #fetch the metrics from microservices every 5s
  evaluation_interval: 5s #show metrics inside dashboard

scrape_configs:
  - job_name: 'accounts' #same as microservice name
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['accounts:8081'] #same as microservice name in docker compose
  - job_name: 'cards'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'cards:8082' ]
  - job_name: 'loans'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'cards:8083' ]
  - job_name: 'gatewayserver'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'gatewayserver:8072' ]
  - job_name: 'eurekaserver'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8070' ]
  - job_name: 'configserver'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8071' ]