build:
  version: "v01"

spring:
  config:
    activate:
      on-profile: "prod"

contacts:
  message: "welcome prod team"
  contactDetails:
    name: "prod"
    email: "a7med.connect@gmail.com"
  phones:
    - 6666666
    - 7777777