server:
  port: 8081
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://localhost:3307/accountsdb
    username: root
    password: 'root'
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: "prod"
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 100000
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration:
          nanos: 100
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        ignore-exceptions:
          - java.lang.NullPointerException # if this exception don't retry
        retry-exceptions:
          - java.util.concurrent.TimeoutException # do a retry for those exceptions
#implementing RateLimiter Pattern (resilience4j)
resilience4j.ratelimiter:
  configs:
    default: #properties for all RateLimiter implementations inside the microservice
      timeoutDuration: 1000 #if number of requests exceeded (1) that's the timeout
      limitRefreshPeriod: 5000 #renew the quota
      limitForPeriod: 1 # 1 request allowed every 5 seconds


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      shutdown:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
   app:
     name: "accounts"
     description: "Ahmed Bank Accounts Application"
     version: "1.0.0"

logging:
  level:
    net:
      ahmed:
        bank:
          accounts: DEBUG
