server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/A-HANAFI/ebank_config.git"
          default-label: main
          clone-on-start: true
          force-pull: true
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

encrypt:
  key: "hellohello654321"

#        native:
#          search-locations: "file:///E://tuto & certifs//SPRING//UDEMY//MicroServices//config"
#          search-locations: "classpath:/config"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

